force-app/main/default/objects/Case_History__c/Case_History__c.object-meta.xml
<CustomObject>
    <label>Histórico de Caso</label>
    <nameField>
        <displayFormat>HC-{00000}</displayFormat>
        <label>Nome</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Históricos de Casos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_History__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso</label>
    <referenceTo>Case_Request__c</referenceTo>
    <relationshipLabel>Históricos de Casos</relationshipLabel>
    <relationshipName>Case_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_History__c/fields/SLA_Met__c.field-meta.xml
<CustomField>
    <fullName>SLA_Met__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SLA Atendido</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case_History__c/fields/Time_Closed__c.field-meta.xml
<CustomField>
    <fullName>Time_Closed__c</fullName>
    <label>Tempo de fechamento</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Case_Request__c/Case_Request__c.object-meta.xml
<CustomObject>
    <label>Solicitação de caso</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Caso ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Solicitação de casos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Request__c/fields/Resolution_Notes__c.field-meta.xml
<CustomField>
    <fullName>Resolution_Notes__c</fullName>
    <description>É um campo para explicar como o caso foi resolvido.</description>
    <inlineHelpText>Explique como foi a solução do caso, suas facilidades e dificuldades.</inlineHelpText>
    <label>Notas de resolução</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>É o progresso que o caso se encontra no momento.</description>
    <inlineHelpText>Coloque o momento em que o caso se encontra no agora.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>Novo</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <label>Em progresso</label>
            </value>
            <value>
                <fullName>Escalated</fullName>
                <label>Escalado</label>
            </value>
            <value>
                <fullName>Closed</fullName>
                <label>Fechado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CaseHistoryUtility_Test.cls
@isTest
private class CaseHistoryUtility_Test {

    @isTest
    static void testCreatingHistoryCase() {
        Test.startTest();
        List<Case_Request__c> casesRequest = TestDataFactory.createRequestCases(1);
        insert casesRequest;

        casesRequest[0].Resolution_Notes__c = 'Testando';
        casesRequest[0].Status__c = 'Closed';
        update casesRequest;

        Test.stopTest();

        Case_Request__c caseRequest = [
            SELECT Id,
                (SELECT Id, Case__c, SLA_Met__c, Time_Closed__c FROM Case_History__r) 
            FROM Case_Request__c 
            WHERE Id = :casesRequest[0].Id
        ];

        Assert.areEqual(1, caseRequest.Case_History__r.size(), 'Should have found a new case history');

        for (Case_History__c hist : caseRequest.Case_History__r) {
            Assert.areEqual(casesRequest[0].Id, hist.Case__c, 'Case History isnt linked to the case');
            Assert.areEqual(true, hist.SLA_Met__c, 'SLA met not true');
            Assert.areNotEqual(null, hist.Time_Closed__c, 'Time closed should not be null');
        }
    }
}