force-app/main/default/objects/Case_History__c/Case_History__c.object-meta.xml
<CustomObject>
    <label>Histórico de Caso</label>
    <nameField>
        <displayFormat>HC-{00000}</displayFormat>
        <label>Nome</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Históricos de Casos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_History__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso</label>
    <referenceTo>Case_Request__c</referenceTo>
    <relationshipLabel>Históricos de Casos</relationshipLabel>
    <relationshipName>Case_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_History__c/fields/SLA_Met__c.field-meta.xml
<CustomField>
    <fullName>SLA_Met__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SLA Atendido</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case_History__c/fields/Time_Closed__c.field-meta.xml
<CustomField>
    <fullName>Time_Closed__c</fullName>
    <label>Tempo de fechamento</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Case_Request__c/Case_Request__c.object-meta.xml
<CustomObject>
    <label>Solicitação de caso</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Caso ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Solicitação de casos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Request__c/fields/ClosedDateTime__c.field-meta.xml
<CustomField>
    <fullName>ClosedDateTime__c</fullName>
    <label>Data e hora de fechamento</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/CaseHistoryUtility.cls
public with sharing class CaseHistoryUtility {
    public static void createCaseHistories(List<Case_Request__c> caseList) {
        Map<String, String> planTypeToRecordTypeId = PlanTypeService.getPlanTypeToRecordTypeIdMap();
        List<Case_History__c> historiesToInsert = new List<Case_History__c>();

        for (Case_Request__c cs : caseList) {
            Datetime closedDate = Datetime.now();
            Boolean slaMet;


            if (cs.RecordTypeId != null) {
                slaMet = SLAService.verifySLA(cs.CreatedDate, cs.ClosedDateTime__c, cs.RecordTypeId, planTypeToRecordTypeId);
            } else {
                slaMet = false;
            }

            Case_History__c history = new Case_History__c(
                Case__c = cs.Id,
                Time_Closed__c = DateTimeUtility.getTimeDifference(cs.createdDate, cs.ClosedDateTime__c),
                SLA_Met__c = slaMet
            );
            historiesToInsert.add(history);
        }

        if (!historiesToInsert.isEmpty()) {
            insert historiesToInsert;
        }
    }
}