force-app/main/default/objects/Case_Request__c/Case_Request__c.object-meta.xml
<CustomObject>
    <label>Solicitação de caso</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Caso ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Solicitação de casos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>É o progresso que o caso se encontra no momento.</description>
    <inlineHelpText>Coloque o momento em que o caso se encontra no agora.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>Novo</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <label>Em progresso</label>
            </value>
            <value>
                <fullName>Escalated</fullName>
                <label>Escalado</label>
            </value>
            <value>
                <fullName>Closed</fullName>
                <label>Fechado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CaseRequestTriggerHandler.cls
public with sharing class CaseRequestTriggerHandler extends TriggerHandler {
    public override void afterUpdate() {
        List<Case_Request__c> closedCases = new List<Case_Request__c>();

        for (Case_Request__c cs : (List<Case_Request__c>) Trigger.new) {
            Case_Request__c oldCs = (Case_Request__c) Trigger.oldMap.get(cs.Id);

            if (cs.Status__c == 'Closed' 
                && oldCs.Status__c != 'Closed') {
                
                closedCases.add(cs);
            }
        }

        if (!closedCases.isEmpty()) {
            CaseHistoryUtility.createCaseHistories(closedCases);
            CaseRequestUtility.updateClosureTime(closedCases);
        }
    }
}