force-app/main/default/objects/Case_Request__c/Case_Request__c.object-meta.xml
<CustomObject>
    <label>Solicitação de caso</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Caso ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Solicitação de casos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Request__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Conta associada</description>
    <inlineHelpText>Conta associada ao caso.</inlineHelpText>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Solicitação de casos</relationshipLabel>
    <relationshipName>CaseRequest</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Request__c/fields/Case_Reason__c.field-meta.xml
<CustomField>
    <fullName>Case_Reason__c</fullName>
    <label>Razão do caso</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Erro de Sistema</fullName>
            </value>
            <value>
                <fullName>Falha de Hardware</fullName>
            </value>
            <value>
                <fullName>Dificuldade de Acesso</fullName>
            </value>
            <value>
                <fullName>Problemas de Conectividade</fullName>
            </value>
            <value>
                <fullName>Solicitação de Instalação</fullName>
            </value>
            <value>
                <fullName>Atualização de Software</fullName>
            </value>
            <value>
                <fullName>Solicitação de Treinamento</fullName>
            </value>
            <value>
                <fullName>Dúvida Operacional</fullName>
            </value>
            <value>
                <fullName>Incidente de Segurança</fullName>
            </value>
            <value>
                <fullName>Consulta sobre Serviços</fullName>
            </value>
            <value>
                <fullName>Reclamação</fullName>
            </value>
            <value>
                <fullName>Sugestão de Melhoria</fullName>
            </value>
            <value>
                <fullName>Outro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Request__c/fields/CaseOrigin__c.field-meta.xml
<CustomField>
    <fullName>CaseOrigin__c</fullName>
    <description>Qual a origem do caso.</description>
    <inlineHelpText>Qual a origem do caso.</inlineHelpText>
    <label>Origem do caso</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Telefone</fullName>
            </value>
            <value>
                <fullName>E-mail</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
            <value>
                <fullName>WhatsApp</fullName>
            </value>
            <value>
                <fullName>Outros</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Request__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contato relacionado ao caso</description>
    <inlineHelpText>Contato relacionado ao caso.</inlineHelpText>
    <label>Contato</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Solicitação de casos</relationshipLabel>
    <relationshipName>CaseRequest</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Request__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Descreva o caso o mais detalhado possível.</description>
    <inlineHelpText>Coloque uma boa descrição que seja possível relembrar facilmente sobre o que se trata depois.</inlineHelpText>
    <label>Descrição</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case_Request__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>A prioridade de um caso determina a situação em que ele se encontra.</description>
    <inlineHelpText>Verifique a descrição que colocou anteriormente e determine a prioridade para esse caso.</inlineHelpText>
    <label>Prioridade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
                <label>Baixa</label>
            </value>
            <value>
                <fullName>Medium</fullName>
                <default>true</default>
                <label>Média</label>
            </value>
            <value>
                <fullName>High</fullName>
                <label>Alta</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Request__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Produto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Computador Desktop</fullName>
            </value>
            <value>
                <fullName>Notebook</fullName>
            </value>
            <value>
                <fullName>Servidor</fullName>
            </value>
            <value>
                <fullName>Impressora</fullName>
            </value>
            <value>
                <fullName>Roteador / Switch</fullName>
            </value>
            <value>
                <fullName>Sistema Operacional</fullName>
            </value>
            <value>
                <fullName>Software Corporativo</fullName>
            </value>
            <value>
                <fullName>Aplicativo Mobile</fullName>
            </value>
            <value>
                <fullName>Sistema de Backup</fullName>
            </value>
            <value>
                <fullName>Firewall / Antivírus</fullName>
            </value>
            <value>
                <fullName>Serviços em Nuvem</fullName>
            </value>
            <value>
                <fullName>Outros Equipamentos</fullName>
            </value>
            <value>
                <fullName>Outro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>É o progresso que o caso se encontra no momento.</description>
    <inlineHelpText>Coloque o momento em que o caso se encontra no agora.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>Novo</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <label>Em progresso</label>
            </value>
            <value>
                <fullName>Escalated</fullName>
                <label>Escalado</label>
            </value>
            <value>
                <fullName>Closed</fullName>
                <label>Fechado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Request__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <description>O assunto geral sobre o que se trata o caso.</description>
    <inlineHelpText>Preencha um assunto que dê uma ideia geral do que se trata o caso.</inlineHelpText>
    <label>Assunto</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Request__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Tipo de suporte oferecido.</description>
    <inlineHelpText>Tipo de suporte oferecido.</inlineHelpText>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Suporte Técnico</fullName>
            </value>
            <value>
                <fullName>Suporte a Software</fullName>
            </value>
            <value>
                <fullName>Suporte a Dispositivos Móveis</fullName>
            </value>
            <value>
                <fullName>Infraestrutura de Rede</fullName>
            </value>
            <value>
                <fullName>Segurança da Informação</fullName>
            </value>
            <value>
                <fullName>Consultoria Tecnológica</fullName>
            </value>
            <value>
                <fullName>Atendimento ao Usuário</fullName>
            </value>
            <value>
                <fullName>Treinamento e Capacitação</fullName>
            </value>
            <value>
                <fullName>Suporte em Nuvem</fullName>
            </value>
            <value>
                <fullName>Outro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
public with sharing class TestDataFactory {
    public static List<Case_Request__c> createRequestCases(Integer numRequestCases) {
        List<Case_Request__c> requestCases = new List<Case_Request__c>();

        List<Account> accounts = createAccounts(1);
        List<Contact> contacts = createContacts(1);

        insert accounts;
        insert contacts;

        for (Integer i = 0; i < numRequestCases; i++) {
            Case_Request__c requestCase = new Case_Request__c(
                Priority__c = 'Low', 
                Status__c = 'New', 
                Subject__c = 'Test Case Request' + i, 
                Description__c = 'Test Case Request Description' + i,
                Account__c = accounts[0].Id,
                Contact__c = contacts[0].Id,
                CaseOrigin__c = 'Telefone',
                Type__c = 'Suporte Técnico',
                Product__c = 'Notebook',
                Case_Reason__c = 'Erro de Sistema'
            );

            requestCases.add(requestCase);
        }

        return requestCases;
    }

    public static List<Account> createAccounts(Integer numAccounts) {
        List<Account> accounts = new List<Account>();

        for (Integer i = 0; i < numAccounts; i++) {
            Account acct = new Account(
                Name = 'Test Account' + i, 
                BillingCity = 'Test City',
                BillingCountry = 'Brazil',
                BillingStreet = 'Test Street',
                BillingPostalCode = '123456',
                Phone = '12345678'
            );

            accounts.add(acct);
        }

        return accounts;
    }

    public static List<Contact> createContacts(Integer numContacts) {
        List<Contact> contacts = new List<Contact>();

        for (Integer i = 0; i < numContacts; i++) {
            Contact contact = new Contact(
                FirstName = 'Test',
                LastName = 'Contact ' + i,
                Email = 'testcontact' + i + '@email.com'
            );

            contacts.add(contact);
        }

        return contacts;
    }
}