force-app/main/default/objects/Case_Request__c/Case_Request__c.object-meta.xml
<CustomObject>
    <label>Solicitação de caso</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Caso ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Solicitação de casos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>É o progresso que o caso se encontra no momento.</description>
    <inlineHelpText>Coloque o momento em que o caso se encontra no agora.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>Novo</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <label>Em progresso</label>
            </value>
            <value>
                <fullName>Escalated</fullName>
                <label>Escalado</label>
            </value>
            <value>
                <fullName>Closed</fullName>
                <label>Fechado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CaseRequestRestResource_Test.cls
@isTest
private class CaseRequestRestResource_Test {

    @isTest
    static void testGetRequestCase() {
        Case_Request__c caseReq = TestDataFactory.createRequestCases(1)[0];
        insert caseReq;

        RestRequest req = new RestRequest();
        req.requestURI = '/CaseRequest/' + caseReq.Id;
        req.httpMethod = 'GET';
        RestContext.request = req;
        RestContext.response = new RestResponse();

        Test.startTest();
        List<CaseRequestRestResource.CaseResponse> responses = CaseRequestRestResource.getCaseRequest();
        Test.stopTest();
        
        System.assertEquals(1, responses.size(), 'Must return with at least one response');
        System.assertEquals(caseReq.Id, responses[0].caseId, 'ID of the case should be equal the ID insert');
        System.assertEquals(caseReq.Status__c, responses[0].status, 'Status have to be equal the case status');
        System.assertNotEquals(null, responses[0].slaMet, 'SLA cant be null');
    }
}