force-app/main/default/objects/PlanConfig__mdt/fields/Plan_Type__c.field-meta.xml
<CustomField>
    <fullName>Plan_Type__c</fullName>
    <label>Plan Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PlanConfig__mdt/fields/Record_Type_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Type_Id__c</fullName>
    <label>Record Type Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PlanTypeService.cls
public with sharing class PlanTypeService {
    public static Map<String, String> getPlanTypeToRecordTypeIdMap() { 
        Map<String, String> mapPlan = new Map<String, String>();

        for (PlanConfig__mdt config : [
            SELECT Plan_Type__c, Record_Type_Id__c FROM PlanConfig__mdt
        ]) {
            mapPlan.put(config.Plan_Type__c, config.Record_Type_Id__c);
        }

        return mapPlan;
    }
}